# MYSQL_CONCPP_DIR = Connector/C++ installation location
# CPPFLAGS = -I $(MYSQL_CONCPP_DIR)/include -L $(MYSQL_CONCPP_DIR)/lib64
# LDLIBS = -lmysqlcppconn8
# CXXFLAGS = -std=c++11
# app : app.cc
MYSQL_CONCPP_DIR= /usr
CPPFLAGS = -I $(MYSQL_CONCPP_DIR)/include -L $(MYSQL_CONCPP_DIR)/lib64
LDLIBS = -lmysqlcppconn8 -lpthread
CXXFLAGS = -std=c++11
 
app : app.cc